2024-06-28 10:05:02,875 INFO: User 12579 NT1 logged in [in c:\Users\Khanh\Desktop\HRM\app.py:1691]
2024-06-28 12:56:50,778 INFO: Cannot specify ',' with 's'. [in c:\Users\Khanh\Desktop\HRM\app.py:361]
2024-06-28 13:28:29,558 INFO: invalid literal for int() with base 10: '1,000,000' [in c:\Users\Khanh\Desktop\HRM\app.py:367]
2024-06-28 13:41:46,856 INFO: [Errno 2] No such file or directory: 'c:\\Users\\Khanh\\Desktop\\HRM\\static/uploads/mau/hopdong/nt1/duoi_o2/vth.xlsx' [in c:\Users\Khanh\Desktop\HRM\app.py:440]
2024-06-28 16:24:48,943 INFO: User 4581 NT2 logged in [in c:\Users\Khanh\Desktop\HRM\app.py:1718]
2024-06-28 17:23:12,423 INFO: unhashable type: 'StyleProxy' [in c:\Users\Khanh\Desktop\HRM\app.py:350]
2024-06-28 17:49:15,902 ERROR: Exception on /muc3_3 [POST] [in C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "c:\Users\Khanh\Desktop\HRM\app.py", line 2435, in inhopdonglaodong
    if "'" in cell.value:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Khanh\Desktop\HRM\app.py", line 1636, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\Khanh\Desktop\HRM\app.py", line 2442, in inhopdonglaodong
    print(e)
          ^
NameError: name 'e' is not defined
2024-06-29 12:40:37,584 ERROR: Exception on /muc10_3 [POST] [in C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Khanh\Desktop\HRM\app.py", line 1673, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\Khanh\Desktop\HRM\app.py", line 3105, in inchamduthopdong
    ngaylamhopdong = request.form.get("ngaylamhd").day
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'day'
2024-06-29 12:50:40,581 ERROR: Exception on /dangkitangcacanhan [POST] [in C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Khanh\Desktop\HRM\app.py", line 3263, in dangkitangcacanhan
    user = laydanhsachtheomst(mst)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-06-29 12:53:50,750 ERROR: Exception on /dangkitangcacanhan [POST] [in C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 892, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Khanh\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'dangkitangcacanhan' did not return a valid response. The function either returned None or ended without a return statement.
